version: "3.9"

services:
  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data