"""create table vacancy

Revision ID: 033e22feff3a
Revises: e5f0d4ba92ff
Create Date: 2024-06-18 00:46:44.156560

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "033e22feff3a"
down_revision: Union[str, None] = "e5f0d4ba92ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vacancies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "status_vacancy",
            sa.Enum("OPEN", "CLOSED", "ARCHIVED", name="statusvacancy"),
            nullable=False,
        ),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("contact_user", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status_response",
            sa.Enum(
                "NO_RESPONSE",
                "CALL",
                "TEST_TASK",
                "REFUSE",
                "OFFER",
                name="statusresponse",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vacancies")
    # ### end Alembic commands ###
